# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Samsung Internet Developer Hub
permalink: /:title.html
excerpt_separator: qwertyuiopsdfghjkl
breakpoint: 640px